### ISSUE TITLE
SFX build fails with babel syntax errors because non-js files that should be handled by a loader are sent to transpiler

### ISSUE THREAD

**Issue by OrKoN** [systemjs/builder#272]
The project that throws the error:

https://www.dropbox.com/s/f0j0s0hz5z10j1b/builder_issue.tar.gz?dl=0

Command to reproduce:
```
jspm bundle-sfx main dist/app.js
```

```
Building the single-file sfx bundle for main.js...
Compiling template: file:///home/alex/ember-vcl/token-input/tmp/example1/application.hbs
Compiling template: file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/github/ember-vcl/token-input@master/templates/vcl-token-input.hbs
Compiling template: file:///home/alex/ember-vcl/token-input/tmp/example2/application.hbs
Compiling template: file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/github/ember-vcl/token@0.1.0/templates/token.hbs
Compiling template: file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/github/ember-vcl/button@0.1.2/templates/vcl-button.hbs
Compiling template: file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/github/ember-vcl/icogram@0.1.2/templates/vcl-icogram.hbs

err  SyntaxError: file:///home/alex/ember-vcl/token-input/tmp/example1/application.hbs: Unexpected token (2:18)
       1 | <h2>Default Form</h2>
> 2 | {{vcl-token-input items=items}}
    |                   ^
       3 | 
         at Parser.pp.raise (file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/npm/babel-core@5.8.21/browser.js:65138:13)
         at Parser.pp.unexpected (file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/npm/babel-core@5.8.21/browser.js:66368:8)
         at Parser.pp.semicolon (file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/npm/babel-core@5.8.21/browser.js:66355:81)
         at Parser.pp.parseExpressionStatement (file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/npm/babel-core@5.8.21/browser.js:65864:8)
         at Parser.parseExpressionStatement (file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/npm/babel-core@5.8.21/browser.js:67012:20)
         at Parser.pp.parseStatement (file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/npm/babel-core@5.8.21/browser.js:65579:21)
         at Parser.parseStatement (file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/npm/babel-core@5.8.21/browser.js:66991:22)
         at Parser.pp.parseBlock (file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/npm/babel-core@5.8.21/browser.js:65879:21)
         at Parser.pp.parseStatement (file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/npm/babel-core@5.8.21/browser.js:65542:19)
         at Parser.parseStatement (file:///home/alex/ember-vcl/token-input/tmp/jspm_packages/npm/babel-core@5.8.21/browser.js:66991:22)
```

**Comment by OrKoN** [comment]
@guybedford I have found that this line is causing the problem: https://github.com/systemjs/builder/blob/master/compilers/esm.js#L49 I guess `var source = load.originalSource;` should be `var source = load.source` because originalSource contains plain handlebars templates and source contains a js version of the template. But if I simply replace this line in the builder I get another error:

```
err  Error: No element indexed by 0
         at ArraySet_at [as at] (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/systemjs-builder/node_modules/source-map/lib/source-map/array-set.js:93:11)
         at SourceMapConsumer.<anonymous> (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/systemjs-builder/node_modules/source-map/lib/source-map/source-map-consumer.js:147:79)
         at Array.map (native)
         at SourceMapConsumer_eachMapping [as eachMapping] (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/systemjs-builder/node_modules/source-map/lib/source-map/source-map-consumer.js:146:16)
         at /home/alex/.npm-packages/lib/node_modules/jspm/node_modules/systemjs-builder/lib/sourcemaps.js:54:24
         at Array.forEach (native)
         at exports.concatenateSourceMaps (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/systemjs-builder/lib/sourcemaps.js:35:19)
         at createOutput (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/systemjs-builder/lib/output.js:70:17)
         at exports.writeOutputs (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/systemjs-builder/lib/output.js:156:16)
         at /home/alex/.npm-packages/lib/node_modules/jspm/node_modules/systemjs-builder/lib/builder.js:218:12
         at lib$rsvp$$internal$$tryCatch (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:493:16)
         at lib$rsvp$$internal$$invokeCallback (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:505:17)
         at lib$rsvp$$internal$$publish (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:476:11)
         at lib$rsvp$asap$$flush (/home/alex/.npm-packages/lib/node_modules/jspm/node_modules/rsvp/dist/rsvp.js:1198:9)
         at process._tickCallback (node.js:355:11)
```

**Comment by guybedford** [comment]
Thanks, I've added https://github.com/systemjs/systemjs/commit/a38da7ed4c1c66e853c20d83375d35100f3453f8 to SystemJS which should resolve this. I don't have time to test it right now, but will come back to this as soon as I can.

**Comment by OrKoN** [comment]
@guybedford I have tried it out - it didn't help. Build still fails and it happens before the translate hook is called.

**Comment by OrKoN** [comment]
I have patched the code locally:

```
if (endsWith(load.address, '.hbs')) {
    source = load.source;
  }
```

So I can get bundles/sfx-bundles working for me. But there are further problems. For example, if I bundle my app dependencies and run app in dev mode I get this error: `Uncaught (in promise) Error: Invalid anonymous System.register module load. If loading a single module, ensure anonymous System.register is loaded via System.import. If loading a bundle, ensure all the System.register calls are named.`.

I would like to add tests for my workflow. Where is the right place to place tests like this?  I would like to test the following: 

1) that one can build and bundle with loader plugins for non-js resources
2) that one can import modules from such bundles

And guidance is welcome.

**Comment by guybedford** [comment]
I've completed the fix for this in https://github.com/systemjs/builder/commit/db0f07ea91580dd4facdac0e887555300f06bddb.

**Comment by OrKoN** [comment]
@guybedford still does not work for me with both of these patches.

**Comment by guybedford** [comment]
@OrKoN I definitely tested it to work. Make sure you're patching the SystemJS dependency within the node_modules folder.

**Comment by OrKoN** [comment]
@guybedford Then probably my fault. I will wait till next release then. Thanks

**Comment by guybedford** [comment]
Published in 0.13.2.

**Comment by OrKoN** [comment]
@guybedford Hi, I see this is happening again with jspm 0.16.6.

**Comment by guybedford** [comment]
@OrKoN thanks, yes I removed this thinking it was no longer necessary due to some changes. Added back in https://github.com/systemjs/builder/commit/f0236c809d9e000ffb2473c823055d17ed33d298.
