### ISSUE TITLE
Deterministic build order

### ISSUE THREAD

**Issue by Mosho1** [systemjs/builder#284]
The bundled output's internal package order seems to be random. I'm using a hash for versioning that means it changes every time, so I always cache-bust when I upload, regardless of actual changes.

**Comment by guybedford** [comment]
Good point, we should make the order well-defined based on the dependency structure.

**Comment by guybedford** [comment]
Fixed by @Munter in https://github.com/systemjs/builder/pull/309.

**Comment by guybedford** [comment]
Released in 0.14.0.

**Comment by carlosagsmendes** [comment]
@Munter and @guybedford I'm facing some issues when hashing due to inconsistencies in the  modules order.

In the [Trace.getTreeModulesPostOrder](https://github.com/systemjs/builder/blob/4953ad9b2acc30c91f0fc24191669d8ea96dadea/lib/trace.js#L642) I get the following order:

![Order in getTreeModulesPostOrder](http://content.screencast.com/users/carlos.mendes/folders/Jing/media/dbe7e62f-9d07-4909-bb38-1c062f316913/2015-10-07_1834.png)

In the `builder.bundle` I get the following order in the `output.modules`:

 ![Order in builderBundle](http://content.screencast.com/users/carlos.mendes/folders/Jing/media/4b404b2e-0394-4c91-90d7-c50b15b5c098/2015-10-07_1837.png)

I'm using the in-memory process:
```
builder.bundle('myModule.js', { minify: true }).then(function(output) {
  output.source;    // generated bundle source
  output.sourceMap; // generated bundle source map
  output.modules;   // array of module names defined in the bundle
});
```

And in the `builder.bundle` I get the following order in the `output.source`:

```
editors/single-file-upload/single-file-upload-template.html!github:systemjs/plugin-text@0.0.2
github:blueimp/jQuery-File-Upload@9.11.2/jquery.fileupload
github:blueimp/jQuery-File-Upload@9.11.2
github:blueimp/jQuery-File-Upload@9.11.2/jquery.fileupload-process
github:blueimp/jQuery-File-Upload@9.11.2/jquery.fileupload-validate
github:blueimp/jQuery-File-Upload@9.11.2/jquery.iframe-transport
editors/single-file-upload/single-file-upload-bootstrapper
editors/single-file-upload/single-file-upload-viewmodel
infrastructure/jquery-file-upload-custom
```

The order is always different.

Shouldn't it always be the same?

Thanks

**Comment by Munter** [comment]
Hmm. There was a big refactoring with breaking changes which happened just around the time where the post order traversal was merged in. Maybe we missed a call to get the order somewhere

**Comment by guybedford** [comment]
@carlosagsmendes thanks for posting! This was an oversight in the promises chains, fixed in https://github.com/systemjs/builder/commit/c8c947e05060cf430ce76f59904ad3c2a0da41ce.

**Comment by carlosagsmendes** [comment]
Thanks @guybedford I've just tested it with the 0.14.9 version and I'm still getting different results with multiple runs.

output.modules order (when building in memory) is still not consistent:

Run1:

![Run1](http://content.screencast.com/users/carlos.mendes/folders/Jing/media/a34568ad-9670-45b6-86d8-61068313a9a8/2015-10-19_1539.png)

Run2:

![Run2](http://content.screencast.com/users/carlos.mendes/folders/Jing/media/c05b6587-32cf-421f-9b58-ffe73ed82f16/2015-10-19_1533.png)

Items 3 and 4 order changed.

Here's how they are being imported:
```
import 'jquery-file-upload';
import 'jquery-ui/ui/widget';
import 'jquery-file-upload/jquery.fileupload-process';
import 'jquery-file-upload/jquery.fileupload-validate';
// This is only for IE9
import 'jquery-file-upload/jquery.iframe-transport';
```

**Comment by guybedford** [comment]
@carlosagsmendes when you say the last export is only for IE9 are you setting that via `metadata.deps` perhaps? I'm just wondering where the non-determinism is creeping in.

**Comment by carlosagsmendes** [comment]
Hi, no, this is just a simple comment so we can remember why we're doing this import. 

Here's a copy of my package.json. Could it be something related with dependencies?

https://gist.github.com/carlosagsmendes/eaa44a2e262e07a98f92#file-package-json-L153

**Comment by guybedford** [comment]
@carlosagsmendes `output.modules` is not actually deterministic, while the build itself should be. Are you definitely seeing the output source file as non-deterministic here as well?
