### ISSUE TITLE
Tests not passing in Windows

### ISSUE THREAD

**Issue by arackaf** [systemjs/builder#531]
I've got a fresh clone of builder.  I've run an npm install.  npm run test fails since I assume that syntax is invalid on my windows machine.  So I manually created the output directory and just ran mocha from the command line.  6 tests are failing, and it's not immediately clear why.

![image](https://cloud.githubusercontent.com/assets/11261266/14019457/e1b9bfbc-f1a0-11e5-9c00-a04904d5e1db.png)

**Comment by arackaf** [comment]
@guybedford I've got a PR almost ready for you on those arithmetic parens (I think I can get them recursive, too...)

I just need to get these tests passing before I'd feel comfortable sending them over.

**Comment by guybedford** [comment]
Did I hear you right on Twitter, or do we still need to tackle these compatibility bugs to get the tests to run in Windows?

**Comment by arackaf** [comment]
No it's still an issue - I commented these tests out - it appears I need to take some special steps to get these Traceur / Babel / Typescript tests working?  Or should they work out of the box?

**Comment by guybedford** [comment]
Ok right, well feel free to send the PR anyway, as the Travis tests won't be affected by having test support in Windows. I've renamed this issue accordingly.

**Comment by arackaf** [comment]
Ok cool - I should have it wrapped up tomorrow.  Thanks.

**Comment by guybedford** [comment]
I'm not sure if this is a Windows bug actually. The current build failures seem to be consistent only in Node 5, due to some random phantomJS bug. I've disabled the phantomjs tests in Node 5 for now to get the builds to pass.

**Comment by arackaf** [comment]
fyi - I'm on Node 4.1.1.

**Comment by guybedford** [comment]
Ah ok that kills that hypothesis then :)

**Comment by arackaf** [comment]
Did you test it on Node 4.1.1?

Also, you ok with a .gitignore change for Jetbrains users?

**Comment by guybedford** [comment]
I haven't got around to the windows testing yet so will come back to that when I can. Sure feel free to put what you like in gitignore!

**Comment by arackaf** [comment]
Ok sent - thanks for being so responsive :)

**Comment by arackaf** [comment]
Let me know if there's anything I can do to try to debug those tests for us Windows types

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/builder/commit/15cd868980ff8ced54c269ebb75d5656360577f1.

**Comment by arackaf** [comment]
Hm, sorry, but those 6 tests are still failing for me.  The tests DO run with `npm run test` but there appears to be something wrong with Babel, TypeScript and Traceur.

As I said, I'm happy to help debug. 

![image](https://cloud.githubusercontent.com/assets/11261266/14067747/7baf0c3e-f431-11e5-8ea5-19004615a1cf.png)

**Comment by guybedford** [comment]
@arackaf odd it's definitely passing for me here. Which version of Node are you running?

**Comment by arackaf** [comment]
Node 4.1.1.  I'll try to find some time to properly debug these tests and find the place where things are failing.

**Comment by guybedford** [comment]
I was testing on the exact same version, and it was a fresh clone, so do let me know what you find.

**Comment by arackaf** [comment]
Further info: npm 3.5.  Windows 10.

I'll debug this when able and let you know where precisely the error is.
