### ISSUE TITLE
Sourcemap line offset using jspm beta

### ISSUE THREAD

**Issue by domagojk** [systemjs/builder#542]
When I am building my app in JSPM beta 12 without minify with source maps, source maps are loaded but it seems incorrectly. If I add breakpoint it misses "real" code by about 3 lines...

I have created simple project with just one .js file:
https://github.com/domagojk/jspm-test
it can be tested here:
http://preview.a4ov40j99qz1tt9w57xeounmy0newmiajacgh7of01nstt9.box.codeanywhere.com:8080/

You can try opening up this page with chrome debugger, with break point in test.js, for example at line 10 - which should actually be in line 7 (inspecting variable "i")

![screen_shot_2016-04-06_at_19 27 26](https://cloud.githubusercontent.com/assets/1868852/14326348/de9f7bf4-fc2d-11e5-8bfa-bc671028f11d.png)

builded file was created with:
`jspm build test.js test.builded.js --skip-rollup`

I am using "--skip-rollup" because without it I got this error
`err  Build output to umd requires the global name to be set.                                                                                               
   Try adding --global-name test or setting --format amd `

**Comment by gcnm-pgeil** [comment]
I am experiencing sourcemap offsets too but started to investigate on this.

**Comment by guybedford** [comment]
My suspicion is that these source maps issues are only affecting ES modules.

**Comment by guybedford** [comment]
(that is building AMD, CommonJS or global modules only should give correct source maps, but let me know if I'm wrong here)

**Comment by guybedford** [comment]
If so, I think this is a Traceur issue. Will do some further testing shortly.

**Comment by guybedford** [comment]
(Traceur applies even when using Babel or TypeScript to transpile)

**Comment by guybedford** [comment]
Ok actually it's the complete opposite here - this is a Babel transpilation bug.

**Comment by guybedford** [comment]
Nope this definitely is a Traceur bug. Unfortunately it's proving hard to track down exactly how it is arising - it seems really subtle as it only applies in certain transpilation cases.

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/builder/commit/ae5a649083492f50fad550c2f4819cb14874b399.

**Comment by guybedford** [comment]
Released in 0.15.16.

**Comment by domagojk** [comment]
@guybedford For me, this error still occurs (I am using JSPM 0.17.0-beta.14)
You can test it out in the same link as before http://preview.a4ov40j99qz1tt9w57xeounmy0newmiajacgh7of01nstt9.box.codeanywhere.com:8080
(explained here in original post)

**Comment by guybedford** [comment]
@domagojk source maps with rollup don't work properly yet until https://github.com/rollup/rollup/issues/409 is supported. If you run with `--skip-rollup` the source maps should line up correctly though.

**Comment by domagojk** [comment]
@guybedford thanks, it works now, but in my app, with linked repositories, source maps are now blank.
I will try to reproduce this bug in simpler project...
