### ISSUE TITLE
Arithmetic bundling in browser application

### ISSUE THREAD

**Issue by bzums** [systemjs/builder#628]
Hey,
i am trying to use arithmetic bundling with parens (which is a great feature btw!!) for an application running in the browser. Roughly, I do the following:
```
    builder.buildStatic('app - [app/**/*]', path.join(PATHS.dist, PATHS.deps), {
      ...
    });
````
and somewhere else:
````
      builder.buildStatic('app - (app/**/* - [app/**/*])', path.join(PATHS.dist, PATHS.app), {
       ...
      });
    });
```

Without explicitly defining a `format` the browser console tells me:
`bundle.js:1876 Uncaught Error: Module must be loaded as AMD or CommonJS`

But out of the box the browser is not capable to handle AMD or CommonJS, is it? 
For example using `cjs` I get:
`Uncaught ReferenceError: module is not defined`
And using `amd`:
`Uncaught ReferenceError: define is not defined`
So Is it possible to build a static bundle with arithmetic bundling features which runs in a browser or what would I have to add to do so?

Best

**Comment by guybedford** [comment]
This should be fixed in the 0.15.23 release!

**Comment by bzums** [comment]
@guybedford Unfortunately I still get the error loading the file build with this command:
```
builder.buildStatic('app - (app/**/* - [app/**/*])', path.join(PATHS.devDist, PATHS.bundleFile), {
        minify: false,
        mangle: false,
        sourceMaps: false
      });
```

**Comment by bzums** [comment]
Still not able to get this running, any ideas?

**Comment by guybedford** [comment]
Make sure to set `globalName: '..'` in the options see https://github.com/systemjs/builder#self-executing-sfx-bundles for more info.

**Comment by bzums** [comment]
@guybedford ah ok makes sense. But assuming that I have two bundles, one for application code and one for external libraries/dependencies (like example above), I would have to declare all external dependencies (everything I import from my application code) in `globalDeps` explicitly?

The error I got is:
```
Unhandled rejection TypeError: Global SFX bundle dependency "@angular/core/index.js" must be configured to an environment global via the globalDeps option.
```

Is there a way to say all external dependencies are in bundle x? Something like:
`globalDeps: { '*': 'externalDependencies' }`
or so? Or am I missing something or missinterpreting the usecase for this functionality or so?

**Comment by guybedford** [comment]
@bzums SFX builds only export a single module, they don't share their internal module structures. The excluded dependencies in an SFX build do need to be relinked manually. Outputting eg AMD or System.register (`format: 'amd' / 'register'`) can make this easier than having to set globalDeps.

Perhaps you may consider using a normal bundle here though as then the internal modules can be shared properly.
