### ISSUE TITLE
buildStatic Module X not declared as a dependency (no dynamic name computing).

### ISSUE THREAD

**Issue by PRR24** [systemjs/builder#669]
Angular 2.0 rc4
boot.ts:
...
import { bootstrap } from "@angular/platform-browser-dynamic";
...

index.html:
...
    <script src="systemjs.config.js"></script>
    <script>
        System.import("app").catch(function(err){ console.error(err); });
    </script>
...
Everything works.

------------------------
gulpfile.js:
....
    var builder = new Builder("", "systemjs.config.js");
    builder.buildStatic("app", "outfile.js", { });
....
Build succeeds.
Replacing the index.html portion above with 
---
    <script src="outfile.js"></script>
---
results:
outfile.js:1 Uncaught TypeError: Module @angular/platform-browser-dynamic not declared as a dependency.

Running builder.bundle("app", { }).then(function(output) ...
output.modules contains item
"node_modules/@angular/platform-browser-dynamic/bundles/platform-browser-dynamic.umd.js"

Am I missing smth really obvious or have I run into some edge case?

**Comment by PRR24** [comment]
New info: systemjs-builder@0.15.25 does not have the problem

**Comment by mvar** [comment]
Same problem here. After upgrading to 0.15.27/0.15.28 modules are not resolved.

**Comment by guybedford** [comment]
Any chance of an isolated test case here? Or can you at least share the SFX output before and after?

**Comment by karlhaas** [comment]
Same here ...
app.js?1471864864797:1 Uncaught TypeError: Module @angular/core not declared as a dependency.

**Comment by guybedford** [comment]
I can't fix anything here until someone can share an isolation or replication.

**Comment by guybedford** [comment]
Fixed in https://github.com/systemjs/builder/commit/7197bfa81d5e5c96a9b906590f9d9d00d82735ee and released in 0.15.29.

**Comment by mvar** [comment]
Works great. Thanks!

**Comment by eelwayadmin** [comment]
Still have this issue : Uncaught TypeError: Module @angular/core not declared as a dependency 
Anyone can help ?

"systemjs": "0.19.38" & "systemjs-builder": "0.15.31"

Conf =
{
...
packages: {
...
'@angular/core': {
        main: 'index.js',
        defaultExtension: 'js'
      },
...
}
...
}
