### ISSUE TITLE
Rollup + sourceMapContents: Mismatched sourcesContent

### ISSUE THREAD

**Issue by arty-name** [systemjs/builder#678]
Hello,

I am using the latest published builder directly, as in `new (require('systemjs-builder'))`. I tried enabling the rollup optimisations, and they work great, but not when I want to have sources inlined in the source map by setting `sourceMapContents` to `true`. Here’s how I use the builder:

```javascript
const builder = new Builder();
builder.loadConfigSync('./systemjs.config.js');
builder.buildStatic('publisher', 'main.js', {
  minify: true,
  sourceMaps: true,
  sourceMapContents: true,
  runtime: false,
  format: 'amd',
  rollup: true,
  externals: ['jquery'],
})
```
With that configuration I get following error:

    Error: Mismatched sourcesContent for: app/scripts/main_bundle/publisher.js
        at node_modules/systemjs-builder/lib/sourcemaps.js:54:21
        at Array.forEach (native)
        at exports.concatenateSourceMaps (node_modules/systemjs-builder/lib/sourcemaps.js:42:19)
        at createOutput (node_modules/systemjs-builder/lib/output.js:63:21)
        at exports.writeOutputs (node_modules/systemjs-builder/lib/output.js:150:16)
        at node_modules/systemjs-builder/lib/builder.js:769:14
        at tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
        at Promise._settlePromiseFromHandler (node_modules/bluebird/js/release/promise.js:504:31)
        at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:561:18)
        at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:606:10)
        at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:685:18)
        at Async._drainQueue (node_modules/bluebird/js/release/async.js:138:16)
        at Async._drainQueues (node_modules/bluebird/js/release/async.js:148:10)
        at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
        at runCallback (timers.js:574:20)
        at tryOnImmediate (timers.js:554:5)

Is this supposed to work?

**Comment by guybedford** [comment]
Thanks, this looks like a bug.

**Comment by diagramatics** [comment]
This might not be that helpful but I traced the action to as far as pointing the problem to `compile.js` around L112-L127. The chunk has a:

```js
return require(compilerMap[format]).compile(mappedLoad, compileOpts, loader);
```

I've tested it with an `esm` module (`format === 'esm'`) that rolls up a dependency. Here's the `mappedLoad` output, specifically `mappedLoad.metadata.sourceMap`:

```js
sources:                                                                                                                                                              
   [ 'modules/@shared/translation/index.js',                                                                                                                            
     'modules/@shared/cookie/index.js',                                                                                                                                 
     'modules/@shared/email-validation/index.js',                                                                                                                       
     'modules/about-careers/index.js' ],  
```

`output.sourceMap` after being compiled returns:

```js
sources: 
   [ 'modules/about-careers/index.js',
     'modules/@shared/cookie/index.js',
     'modules/@shared/email-validation/index.js',
     'modules/about-careers/index.js' ],
```

`modules/@shared/translation/index.js` is the rolled up file, combined into `modules/about-careers/index.js`. The sources got duped and `sourcemaps.js` then maps the replaced sourcemap to the contents of `translation`, then compares to `about-careers`'s content. Hence the error.

So I'm assuming the action is in `compilers/esm.js`? Or even the other compilers as well?

**Comment by guybedford** [comment]
It seems like this is resolved in https://github.com/systemjs/builder/pull/715.

**Comment by guybedford** [comment]
Released in 0.15.33.

**Comment by alexisvincent** [comment]
Still getting this issue. Seems to be caused because two different files are being compared.

`app/components/index.js`
```javascript
/**
 * Copyright 2016 Alexis Vincent (http://alexisvincent.io)
 */
export * as Icon from './Icon.js'
export {default as Image} from './ImagePreloader.js'
export * as Modal from './Modal.js'
export * as ClickContext from './ClickContext.js'
export {default as Nav} from './Nav/Nav.js'
```

`app/actions/index.js`
```javascript
export * from './users.js'
export * from "./boosters.js"
export * from './cart.js'
export * from './dogs.js'
export * from './flavours.js'
```

**Comment by guybedford** [comment]
@alexisvincent see also https://github.com/systemjs/builder/issues/743 where it seems it may be worth reverting #715. Let me know if perhaps that helps or if you have any suggestions here at all.

**Comment by alexisvincent** [comment]
@guybedford Will test now and let you know :)

**Comment by alexisvincent** [comment]
@guybedford I can confirm that reverting #715 fixes my issue
